name: Refresh POI Cache

on:
  #schedule:
    #- cron: "0 0 1 * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  poi-refresh:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests
          pip install pandas
          pip install shapely
          pip install geopandas
          pip install pyogrio

      - name: Build POI cache
        run: python build_poi_cache.py

      - name: Commit updated cache
        run: |

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add poi_cache.geojson

          git commit -m "Refresh POI cache" || echo "No changes"

          git push
